/**
 * Learner-facing briefs for review and challenge exercises.
 * Each value is extractTaskBrief() of the authored markdown in content/tracks.
 * apps/web/__tests__/task-brief.test.ts fails if a value drifts.
 */
export const AUTHORED_BRIEFS: Readonly<Record<string, string>> = {
  'go-challenge-001':
    '# Challenge: String Reverser\n\n## Requirements\n\nCreate a string manipulation package with the following functions:\n\n1. **Reverse(s string) string** - Reverses a string\n2. **ReverseWords(s string) string** - Reverses the order of words (not characters)\n3. **IsPalindrome(s string) bool** - Checks if a string is a palindrome (case-insensitive, ignores spaces)\n4. **CountVowels(s string) int** - Counts the number of vowels in a string\n\nWrite your complete implementation below:',
  'go-challenge-002':
    '# Challenge: Thread-Safe Counter\n\n## Requirements\n\nCreate a `Counter` type that is safe for concurrent use:\n\n1. **NewCounter(initial int) *Counter** - Creates a new counter with initial value\n2. **Increment() int** - Increments by 1 and returns new value (thread-safe)\n3. **Decrement() int** - Decrements by 1 and returns new value (thread-safe)\n4. **Add(n int) int** - Adds n and returns new value (thread-safe)\n5. **Value() int** - Returns current value (thread-safe)\n6. **Reset()** - Resets to 0 (thread-safe)\n\nWrite your complete implementation below:',
  'go-challenge-003':
    '# Challenge: Rate Limiter\n\n## Requirements\n\nCreate a `RateLimiter` type with the following features:\n\n1. **NewRateLimiter(rate int, capacity int) *RateLimiter** - Create limiter with tokens/second and bucket size\n2. **Allow() bool** - Check if request is allowed (consumes token)\n3. **AllowN(n int) bool** - Check if N requests are allowed\n4. **Wait()** - Block until token available\n5. **Remaining() int** - Get remaining tokens\n6. **Reset()** - Reset to full capacity\n\nWrite your complete implementation below:',
  'go-challenge-004':
    '# Challenge: Worker Pool\n\n## Requirements\n\nCreate a `WorkerPool` type with the following features:\n\n1. **NewWorkerPool(numWorkers int) *WorkerPool** - Create pool with N workers\n2. **Start()** - Start all workers\n3. **Submit(job Job)** - Submit job to be processed\n4. **Stop()** - Gracefully shutdown all workers\n5. **Stats() PoolStats** - Get pool statistics\n\nWrite your complete implementation below:',
  'go-challenge-005':
    '# Challenge: HTTP Router\n\n## Requirements\n\nCreate a `Router` type with the following features:\n\n1. **NewRouter() *Router** - Create new router\n2. **Handle(method, path string, handler HandlerFunc)** - Register route\n3. **GET/POST/PUT/DELETE(path, handler)** - HTTP method shortcuts\n4. **ServeHTTP(w ResponseWriter, r *Request)** - Implement http.Handler\n5. **Path parameters** - Support :param and *wildcard\n6. **Middleware support** - Chain middleware functions\n\nWrite your complete implementation below:',
  'go-review-001':
    'You asked a model for a helper that shortens a string to a maximum number of\ncharacters, adding an ellipsis when it cuts. It produced this, with tests. The\ntests pass.\n\nIt is still wrong: give it text containing any non-ASCII character — an\naccent, a CJK ideograph, an emoji — and it can slice a character in half,\nreturning bytes that are not valid UTF-8. Downstream that renders as `�`, or\nbreaks a JSON encoder, depending on who touches it first. Nothing panics, so\nnobody notices until the text is user-facing.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'go-review-002':
    "You asked a model to remove duplicates from a slice of strings. The spec was\ntwo sentences:\n\n> Return a new slice with duplicates removed, keeping the first occurrence of\n> each value in its original position. The input slice is not modified.\n\nIt produced this, with tests. The tests pass, and the returned elements are\nalways exactly right.\n\nBoth promises are still broken. The function sorts — which reorders the output\n*and* writes through to the caller's slice, because `sort.Strings` works in\nplace on the memory you handed over. A caller who lent you their data gets it\nback shuffled. The shipped suite never looks at the input afterwards and only\never asserts membership, so it proves neither promise.\n\nFind the defect and fix it. You are graded on tests you cannot see.",
  'go-review-003':
    'You asked a model for a config lookup with a proper error contract:\n\n> `Lookup(store, key)` returns the value, or an error. When the key is\n> missing, the returned error matches `errors.Is(err, ErrNotFound)`, so\n> callers can branch on it without parsing strings. Errors carry the key in\n> their message for logs.\n\nIt produced this, with tests. The tests pass — the messages read exactly\nright.\n\n`errors.Is` returns false on every error it produces. `fmt.Errorf` with `%v`\nformats the sentinel *into the text* and drops it from the error chain; `%w`\nis the verb that keeps the chain intact, and it is one character away. The\nshipped suite asserts on `err.Error()` substrings — the string is identical\neither way, which is why text-matching tests are structurally unable to\ncatch this. Every caller who wrote the `errors.Is` branch the spec promised\nfalls through to the generic path.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'go-spec-001':
    'Ask for "mask this card number" and you will get something that works on\n`4242424242424242`. It will also do *something* with `4242 4242 4242 4242`,\nand with the 4-digit test value support keeps in a fixture — and what it\ndoes is a decision somebody made without telling you.\n\nHere is the description, stated properly:\n\n> `MaskCard(number)` masks a card number for display. Every digit except the\n> last four becomes `*`. Characters that are not digits — spaces, dashes —\n> are preserved in their positions. Masking counts digits, not characters.\n> An input with four or fewer digits is returned unchanged.\n\nBelow are five implementations. One satisfies that description. Four satisfy\na reading of it that skips one sentence — and all five look fine on the\ndemo input.\n\n**Your job is not to write `MaskCard`.** It is to write the cases that\naccept the correct implementation and reject each of the other four.',
  'go-tool-001':
    'This exercise is real. This platform\'s Go track shipped a lookup helper\nwhose missing-key error was built with `fmt.Errorf("lookup %q: %v", key,\nErrNotFound)`. The message read perfectly. `errors.Is` returned false\nforever — `%v` formats the sentinel into the text and drops it from the\nchain, and `%w` is one character away. Every test that matched message\nsubstrings passed, because the substring is identical either way.\n\nReading does not catch this: the two verbs look alike and the bug only\nshows at a call site three packages away. A rule catches it on every line,\nforever.\n\nWrite `FindBrokenWraps`. It scans Go source and reports every line\ncontaining an `fmt.Errorf` call whose format string uses `%v` while an\nerror value is among the arguments — an identifier named `err`, ending in\n`Err`, or starting with `Err` (the sentinel convention). A format that uses\n`%w` anywhere keeps its chain and is never a finding, even if `%v` also\nappears in it.',
  'py-challenge-001':
    "# Challenge: Temperature Converter\n\n## Requirements\n\nCreate a temperature conversion module with the following functions:\n\n1. **celsius_to_fahrenheit(celsius: float) -> float** - Convert Celsius to Fahrenheit\n2. **fahrenheit_to_celsius(fahrenheit: float) -> float** - Convert Fahrenheit to Celsius\n3. **celsius_to_kelvin(celsius: float) -> float** - Convert Celsius to Kelvin\n4. **kelvin_to_celsius(kelvin: float) -> float** - Convert Kelvin to Celsius\n5. **convert_temperature(value: float, from_unit: str, to_unit: str) -> float** - Universal converter\n\n## Constraints\n\n- Validate that temperatures don't go below absolute zero\n- Raise `ValueError` for invalid temperatures\n- Support unit strings: 'C', 'F', 'K' (case-insensitive)\n- Round results to 2 decimal places\n\nWrite your complete implementation below:",
  'py-challenge-002':
    '# Challenge: File Statistics Analyzer\n\n## Requirements\n\nCreate a `FileStats` class that analyzes text files and provides the following statistics:\n\n1. **Constructor** - Accepts a file path string\n2. **line_count() -> int** - Returns total number of lines\n3. **word_count() -> int** - Returns total number of words\n4. **char_count() -> int** - Returns total number of characters (including whitespace)\n5. **char_count_no_spaces() -> int** - Returns character count excluding spaces\n6. **average_word_length() -> float** - Returns average word length rounded to 2 decimals\n7. **most_common_word() -> str | None** - Returns the most frequently occurring word (case-insensitive)\n8. **unique_words() -> int** - Returns count of unique words\n\n## Constraints\n\n- Handle file not found errors gracefully\n- Words are separated by whitespace\n- Ignore punctuation when counting words\n- Empty files should return 0 for counts and None for most_common_word\n- Strip newlines when reading\n\nWrite your complete implementation below:',
  'py-challenge-003':
    '# Challenge: Database Context Manager\n\n## Requirements\n\nCreate a `DatabaseConnection` context manager with the following features:\n\n1. **__enter__()** - Opens connection and returns self\n2. **__exit__()** - Closes connection, handles exceptions\n3. **execute(query: str, params: tuple) -> Cursor** - Execute SQL query\n4. **commit()** - Commit transaction\n5. **rollback()** - Rollback transaction on error\n6. **@transaction decorator** - Auto-commits or rolls back\n\n## Constraints\n\n- Use contextlib or implement context manager protocol\n- Auto-rollback on exceptions\n- Connection pooling simulation\n- Log all operations\n- Handle nested transactions\n\nWrite your complete implementation below:',
  'py-challenge-004':
    '# Challenge: Async Task Queue\n\n## Requirements\n\nCreate an `AsyncTaskQueue` class with the following features:\n\n1. **__init__(max_concurrency: int = 5)** - Initialize with max concurrent tasks\n2. **add(task: Callable) -> Task** - Add task to queue, return Task object\n3. **run() -> None** - Start processing queue\n4. **wait() -> None** - Wait for all tasks to complete\n5. **size() -> int** - Get queue size\n6. **pending() -> int** - Get number of pending tasks\n7. **completed() -> int** - Get number of completed tasks\n\n## Constraints\n\n- Use asyncio for async operations\n- Respect max concurrency limit\n- Handle task errors gracefully\n- Support task cancellation\n- Track task status (pending, running, completed, failed)\n\nWrite your complete implementation below:',
  'py-challenge-005':
    '# Challenge: Simple ORM\n\n## Requirements\n\nCreate an ORM system with the following features:\n\n1. **Model base class** - Base class for all models\n2. **Field types** - IntegerField, StringField, TextField, DateTimeField\n3. **objects manager** - QuerySet for database operations\n4. **filter(**kwargs)** - Filter records\n5. **all()** - Get all records\n6. **first()** - Get first record\n7. **get(id)** - Get record by ID\n8. **save()** - Save instance\n9. **delete()** - Delete instance\n\n## Constraints\n\n- Use metaclasses for model definition\n- Support method chaining on QuerySet\n- Auto-manage created_at/updated_at timestamps\n- Lazy evaluation for queries\n- Support basic field validation\n- **The runtime has no `sqlite3` module.** Persist however you like — a JSON\n  file behind the path you are given is enough. The exercise is about the ORM\n  layer, not the storage engine.\n\nWrite your complete implementation below:',
  'py-review-001':
    'You asked a model for a retry helper with backoff. It produced this, with tests.\nThe tests pass.\n\nIt retries one time fewer than the caller asked for. On a flaky service that is\nthe difference between a request that recovers and one that surfaces as an error\nto a user — and nothing about the code looks wrong.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'py-review-002':
    'You asked a model for a small helper: add a tag to a list of tags, returning\nthe list; when no list is given, start a fresh one. It produced this, with\ntests. The tests pass.\n\nCall it twice without a list and the second call returns *both* tags. Default\nargument values in Python are evaluated once, at `def` time — that `[]` is a\nsingle list object created when the module loads, shared by every call that\nomits the argument, accumulating forever. Each test here calls the function\nonce and asserts on that one result, so the suite cannot meet the bug: it\nlives *between* calls.\n\nThis is the oldest trick in the Python interview book precisely because\ngenerated code and hurried code both keep producing it.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'py-review-003':
    'You asked a model for a small factory: given a list of discount rates, build\none pricing function per rate. It produced this, with a test. The test\npasses.\n\nBuild handlers for `[0.1, 0.2, 0.3]` and all three apply thirty percent.\nA Python closure captures the *variable*, not the value it held: every\nlambda shares the single loop variable `rate`, reads it at call time, and by\ncall time the loop is long finished — `rate` holds its final value for\neveryone. The shipped test uses a one-element list, the only length at\nwhich "each lambda gets its own rate" and "every lambda gets the last rate"\nare the same claim.\n\nThis bug has a decades-old idiom for a fix, and models reproduce the bug\nmore often than the idiom.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'py-spec-001':
    '"Split this on commas and clean it up" is a request that sounds complete and is\nnot. Whether `Python, python` is one tag or two, and whether the result comes\nback in the order it was written, are decisions somebody is going to make — and\nif you did not make them, you will find out which way they went a long time\nlater, from a bug report.\n\nHere is the description, stated properly:\n\n> `parse_tags(value)` turns a comma-separated string into a list of tags. Each\n> tag is lowercased and has its surrounding whitespace removed. Tags that are\n> empty after that are dropped. Duplicates are removed, keeping the first\n> occurrence. The remaining tags stay in the order they appeared.\n\nBelow are six implementations. One satisfies that description. Five satisfy a\nreading of it that skips one sentence — and all five look fine.\n\n**Your job is not to write `parse_tags`.** It is to write the cases that accept\nthe correct implementation and reject each of the other five.\n\nTwo of the wrong ones are worth thinking about before you start. One deduplicates\nby sorting, so it agrees with the correct implementation on every input that was\nalready in alphabetical order. Another never deduplicates at all, so it agrees on\nevery input with no repeats. Neither is exposed by an input you would type\nwithout meaning to.',
  'py-tool-001':
    'This exercise is real. Content in this platform is markdown with frontmatter,\nand the importer upserts on `(parent, slug)`. Two files under the same parent\nclaiming the same slug is not an error at any layer: both parse, both import,\nand the second silently overwrites the first. The exercise you wrote just\ndisappears, and the only symptom is a number that should have gone up and did\nnot.\n\nNothing catches that except a check that looks across files — which is why it\nhas to be a tool and not a habit.\n\nWrite `find_slug_collisions`.',
  'py-tool-002':
    "This exercise is real. This platform's exercises are markdown files full of\nfenced code blocks, and twice in one day a file shipped with its final\nfence unclosed - the author wrote the closing code, and not the closing\ndelimiter. Markdown does not error: everything after the open fence\nbecomes one endless code block, the sections below it vanish, and the\nfile looks complete in an editor because the content is all there.\n\nBoth were caught by a validator, in milliseconds, at the door. That rule\ndeserves to exist everywhere markdown does.\n\nWrite `find_unclosed_fences`. It scans documents and reports every fence\nthat opens and never closes. A fence is a line whose first non-space\ncharacters are three backticks; an opening fence may carry a language tag\nafter the backticks. Fences do not nest - inside an open fence, the next\nfence line closes it.",
  're-challenge-001':
    "# Challenge: useLocalStorage Hook\n\n## Requirements\n\nCreate a custom React hook `useLocalStorage` with the following features:\n\n1. **Accepts two parameters**: `key` (string) and `initialValue` (any JSON-serializable value)\n2. **Returns a tuple**: `[value, setValue]` similar to useState\n3. **Persists to localStorage**: Value is saved to localStorage on change\n4. **Reads from localStorage**: Initial value comes from localStorage if available\n5. **Handles JSON serialization**: Properly stringify/parse values\n6. **Type-safe**: Works with TypeScript generics\n\n## Constraints\n\n- Handle localStorage being unavailable (SSR, private browsing)\n- Handle JSON parse errors gracefully\n- Sync across tabs using storage event\n- Don't use external libraries\n\nWrite your complete implementation below:",
  're-challenge-002':
    "# Challenge: Debounced Search Component\n\n## Requirements\n\nCreate a `DebouncedSearch` component with the following features:\n\n1. **Search input** - Text input for search queries\n2. **Debounced search** - Wait 300ms after typing stops before searching\n3. **Loading state** - Show loading indicator while searching\n4. **Results display** - Display search results in a list\n5. **Error handling** - Show error message if search fails\n6. **Clear button** - Button to clear search and results\n\n## Props\n\n- `onSearch: (query: string) => Promise<SearchResult[]>` - Search function\n- `placeholder?: string` - Input placeholder\n- `debounceMs?: number` - Debounce delay (default 300)\n\n## Constraints\n\n- Cancel pending requests when new search starts\n- Don't search empty queries\n- Handle component unmount during async operations\n- Use React hooks (useState, useEffect, useCallback, useRef)\n\nWrite your complete implementation below:",
  're-challenge-003':
    '# Challenge: Virtualized List\n\n## Requirements\n\nCreate a `VirtualizedList` component with the following features:\n\n1. **Accepts items array** - List of items to render\n2. **itemHeight** - Fixed height per item (pixels)\n3. **containerHeight** - Visible container height\n4. **overscan** - Number of items to render outside viewport\n5. **onScroll** - Scroll event callback\n6. **onReachEnd** - Callback when scrolling near end (infinite scroll)\n\n## Constraints\n\n- Only render visible items + overscan\n- Maintain scroll position\n- Handle dynamic item heights (optional)\n- Use requestAnimationFrame for scroll handling\n- Support keyboard navigation\n\nWrite your complete implementation below:',
  're-challenge-004':
    '# Challenge: Form Validation Hook\n\n## Requirements\n\nCreate a `useForm` hook with the following features:\n\n1. **initialValues** - Initial form values object\n2. **validationRules** - Validation rules per field\n3. **register(name)** - Register field with validation\n4. **handleSubmit(onSubmit)** - Handle form submission\n5. **errors** - Validation errors object\n6. **touched** - Touched fields tracking\n7. **isSubmitting** - Submission state\n8. **isValid** - Form validity flag\n9. **resetForm()** - Reset to initial values\n10. **setFieldValue(name, value)** - Manually set field value\n\n## Constraints\n\n- Support multiple validation rules per field\n- Async validation support (e.g., check username availability)\n- Real-time validation on blur\n- Validate on change (optional)\n- Type-safe with TypeScript generics\n\nWrite your complete implementation below:',
  're-challenge-005':
    "# Challenge: Infinite Scroll with Caching\n\n## Requirements\n\nCreate an `InfiniteScroll` component with the following features:\n\n1. **fetchData callback** - Async function to fetch page of data\n2. **itemHeight** - Fixed/predicted item height\n3. **threshold** - How close to bottom before fetching\n4. **Cache results** - Don't refetch loaded pages\n5. **Loading states** - Per-page loading indicators\n6. **Error handling** - Retry failed pages\n7. **Virtual scrolling** - Only render visible items\n\n## Constraints\n\n- Cancel pending requests on unmount\n- Handle scroll position during data loading\n- Support pull-to-refresh\n- Debounce scroll events\n- Memory-efficient (cleanup old cache)\n\nWrite your complete implementation below:",
  're-review-001':
    'You asked a model for a todos reducer: add, toggle, clear completed. It\nproduced this, with tests. The tests pass, and the data is always correct.\n\nMounted in a component, the list stops re-rendering. React decides whether\nanything changed by comparing references — `Object.is(prev, next)` — and this\nreducer returns the same object it was given, freshly mutated. The contents\nare right; the identity says "nothing happened". A test suite that only ever\ninspects contents is structurally unable to notice, which is why all of these\npass.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  're-review-002':
    "You asked a model for a countdown hook: give it a number of seconds, get back\nthe seconds remaining, ticking down once per second and stopping at zero. It\nproduced this, with a test. The test passes.\n\nThe countdown ticks exactly once and freezes. The interval callback was\ncreated during the first render, closed over that render's `seconds`, and\ncomputes `start - 1` from it forever — every tick after the first sets the\nsame value. The shipped test advances the clock exactly one second, which is\nthe one duration for which a frozen countdown and a working one are\nindistinguishable.\n\nFind the defect and fix it. You are graded on tests you cannot see.",
  're-review-003':
    "You asked a model for a hook that loads a user's name by id. It produced\nthis, with a test. The test passes.\n\nSwitch ids while a request is in flight and the screen can end up showing\nthe *previous* user: each effect run fires a request, and whichever response\nlands last writes state last — the component has no idea that answer was for\na question it stopped asking. The shipped test resolves responses in\nrequest order, which is the one schedule real networks refuse to guarantee.\n\nNothing here needs a lock. It needs the effect to notice its own\nobsolescence, which is exactly what the cleanup function exists to signal.\n\nFind the defect and fix it. You are graded on tests you cannot see.",
  're-spec-001':
    "Every React codebase has a `cn()`. Ask for one and you will get something\nthat handles `cn('btn', 'active')`. It will also do *something* with\n`false && 'active'`, with `{ hidden: isHidden }`, and with a nested array\nfrom a variadic helper — and each of those somethings is a decision\nsomebody made without telling you.\n\nHere is the description, stated properly:\n\n> `cn(...args)` builds a className string. Strings are included as they\n> are. Falsy arguments — `false`, `null`, `undefined`, the empty string —\n> are skipped entirely. An object contributes each of its keys whose value\n> is truthy. Arrays are flattened, and the flattening is recursive. The\n> result joins what remains with single spaces, with no leading or trailing\n> whitespace.\n\nBelow are five implementations. One satisfies that description. Four\nsatisfy a reading of it that skips one sentence — and all five agree on\n`cn('btn', 'active')`.\n\n**Your job is not to write `cn`.** It is to write the cases that accept\nthe correct implementation and reject each of the other four.",
  're-tool-001':
    'This exercise is real in shape: this platform\'s context exercises exist\nbecause models write `variant="destructive" size="sm"` against design\nsystems whose props are `intent` and `compact` — the famous names, not the\nreal ones. A human reviewer misses it for the same reason the model\nguessed it: it *looks* standard.\n\nThe props table already exists. The gap is that nothing holds usages to\nit, so the wrong name is discovered by the TypeScript build at best and by\na rendering bug at worst. A rule closes the gap at the door.\n\nWrite `findUnknownProps`. Given a component name, its allowed prop names,\nand source files, it reports every attribute passed to that component that\nis not in the allowed set. Attributes appear as `name=...` or as bare\nboolean shorthand (`busy`). Spreads (`{...rest}`) are not attributes and\nare ignored. `children` never appears as an attribute and needs no\nspecial case.',
  'ru-challenge-001':
    "# Challenge: Option Utilities\n\n## Requirements\n\nCreate a module with utility functions for `Option<T>`:\n\n1. **is_some_and<T, F>(opt: Option<T>, f: F) -> bool** - Returns true if Some and predicate returns true\n2. **zip_options<T, U>(opt1: Option<T>, opt2: Option<U>) -> Option<(T, U)>** - Combines two Options\n3. **first_some<T>(opts: &[Option<T>]) -> Option<&T>** - Returns first Some value in slice\n4. **count_some<T>(opts: &[Option<T>]) -> usize** - Counts number of Some values\n5. **flatten_options<T>(opts: &[Option<Option<T>>]) -> Option<T>** - Flattens nested options\n\n## Constraints\n\n- Use generics where appropriate\n- Follow Rust idioms and best practices\n- Handle edge cases (empty slices, all Nones, etc.)\n- Don't use unwrap() - handle all cases explicitly\n\nWrite your complete implementation below:",
  'ru-challenge-002':
    '# Challenge: Safe Division Calculator\n\n## Requirements\n\nCreate a division module that handles errors gracefully:\n\n1. **DivisionError enum** - With variants: `DivisionByZero`, `Overflow`, `InvalidInput`\n2. **divide(a: f64, b: f64) -> Result<f64, DivisionError>** - Safe division\n3. **safe_divide(a: f64, b: f64) -> Option<f64>** - Returns None on error\n4. **divide_all(nums: &[f64], divisor: f64) -> Result<Vec<f64>, DivisionError>** - Divide all numbers\n5. **checked_divide(a: f64, b: f64) -> Result<f64, DivisionError>** - Also checks for overflow\n\n## Constraints\n\n- Implement `Display` and `std::error::Error` for `DivisionError`\n- Handle division by zero\n- Handle infinity results (overflow)\n- Handle NaN inputs as invalid\n\nWrite your complete implementation below:',
  'ru-challenge-003':
    '# Challenge: TTL Cache\n\n## Requirements\n\nCreate a `Cache<K, V>` struct with the following features:\n\n1. **new() -> Self** - Create new cache\n2. **insert(key: K, value: V, ttl: Duration) -> Option<V>** - Insert with TTL\n3. **get(&self, key: &K) -> Option<V>** - Get value if not expired\n4. **remove(&mut self, key: &K) -> Option<V>** - Remove key\n5. **len(&self) -> usize** - Count non-expired entries\n6. **clear(&mut self)** - Remove all entries\n7. **cleanup_expired(&mut self) -> usize** - Remove expired, return count\n\n## Constraints\n\n- Thread-safe using RwLock or Mutex\n- Auto-expire entries on access\n- Background cleanup optional\n- Generic over key and value types\n\nWrite your complete implementation below:',
  'ru-challenge-004':
    '# Challenge: HTTP Request Builder\n\n## Requirements\n\nCreate a `RequestBuilder` struct with the following features:\n\n1. **new(method: Method, url: &str) -> Self** - Create new builder\n2. **header(key: &str, value: &str) -> Self** - Add header\n3. **headers(map: HashMap<&str, &str>) -> Self** - Add multiple headers\n4. **query(key: &str, value: &str) -> Self** - Add query parameter\n5. **body<T: Serialize>(data: &T) -> Self** - Set JSON body\n6. **timeout(duration: Duration) -> Self** - Set timeout\n7. **bearer_token(token: &str) -> Self** - Set auth token\n8. **build() -> Result<Request, Error>** - Build final request\n\n## Constraints\n\n- Fluent/builder pattern (method chaining)\n- Proper error handling\n- URL encoding for query params\n- JSON serialization for body\n- Clone-friendly builder\n\nWrite your complete implementation below:',
  'ru-challenge-005':
    '# Challenge: Minimal Async Runtime\n\n## Requirements\n\nCreate a minimal async runtime with the following features:\n\n1. **Runtime struct** - Main runtime executor\n2. **spawn(future) -> JoinHandle** - Spawn async task\n3. **block_on(future)** - Run async code to completion\n4. **yield_now()** - Yield execution to other tasks\n5. **sleep(duration)** - Async sleep\n6. **Channel mpsc** - Multi-producer single-consumer channel\n\n## Constraints\n\n- Use Pin and Future traits\n- Implement Waker correctly\n- Fair task scheduling (round-robin)\n- Handle panics gracefully\n- No external async runtime dependencies\n\nWrite your complete implementation below:',
  'ru-review-001':
    'You asked a model for a leaderboard helper: the top `n` scores, highest first.\nThe spec had one hedge in it, because score data comes from a parser and\nparsers produce garbage:\n\n> Entries that are NaN are skipped, never returned, and never crash the\n> function.\n\nIt produced this, with tests. The tests pass — every score in them is a clean,\nwell-behaved float.\n\nOne NaN in the input and the whole thing panics. `partial_cmp` returns an\n`Option` precisely because floats are not totally ordered, and the generated\ncode answered that inconvenience with `.unwrap()` — the compiler stopped\nasking, so it looked handled. This is the most common way a float panic\nreaches production in Rust: not arithmetic, but sorting.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'ru-review-002':
    'You asked a model for the smallest possible helper: how much of a usage budget\nis left. The spec covered the one interesting case:\n\n> If more than the budget has been spent, the remaining amount is 0 — never\n> negative, never an error.\n\nIt produced this, with tests. The tests pass — every one of them spends less\nthan the budget.\n\nThe first caller who overspends panics the thread. `total - spent` on unsigned\nintegers panics on underflow in debug builds, and in release builds silently\nwraps to a number a little under eighteen quintillion — which a billing page\nwill happily display. The generated tests never crossed the boundary the spec\nwas specifically about, so the suite proves the easy half and skips the half\nthat was the point.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'ru-review-003':
    'You asked a model for a moving average over a series, and because input\narrives from a config file, the spec spelled out the nonsense cases:\n\n> `moving_average(values, window)` returns the average of each consecutive\n> `window` values. A window of zero, or one larger than the series, yields an\n> empty vector — never a panic. This runs in a request handler.\n\nIt produced this, with tests. The tests pass — every one of them uses a\nsensible window on a longer series.\n\nBoth named edge cases panic. `slice::windows` panics outright when its\nargument is zero — the documentation says so in one sentence — and while an\noversized window is handled by `windows` itself (it yields nothing), this\nimplementation never gets there: it computes `values.len() - window + 1` on\nunsigned integers first, and underflow panics in debug builds. Two guards\nthe spec asked for by name, both missing, both invisible to a suite that\nonly feeds the function sense.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'ru-spec-001':
    'Ask for "format seconds as h/m/s" and you will get something that turns\n`4953` into `1h 22m 33s`. It will also do *something* with `0`, with\n`3600`, and with `62` — and each of those somethings is a decision somebody\nmade without telling you.\n\nHere is the description, stated properly:\n\n> `format_duration(secs)` renders a duration for humans. Units are `h`,\n> `m`, `s`, space-separated. A unit with a zero value is omitted — except\n> that a zero duration renders as `"0s"`, never as an empty string. Values\n> are not zero-padded. The largest unit is hours; hours may exceed 24.\n\nBelow are five implementations. One satisfies that description. Four\nsatisfy a reading of it that skips one sentence — and all five agree on\n`4953`.\n\n**Your job is not to write `format_duration`.** It is to write the cases\nthat accept the correct implementation and reject each of the other four.',
  'ru-tool-001':
    "This exercise is real. This platform's Rust track shipped a leaderboard\nhelper that sorted with `partial_cmp(a).unwrap()`. Every test passed —\nevery score in them was a clean float — and the first NaN in real data\npanicked the thread. The `.unwrap()` read as confidence. It was a deferral:\n\"this cannot fail\" spelled in a way the compiler stops asking about.\n\nIn a test, unwrap is fine — a panic *is* the failure report. In library\ncode it is somebody else's outage. The two live in the same file, which is\nwhy reading misses them and a rule does not.\n\nWrite `find_unwraps`. It scans Rust source and reports every occurrence of\n`.unwrap()` that appears *before* the file's `#[cfg(test)]` line — the\nconvention that puts test modules at the bottom of the file. Everything\nfrom that line down is test code and exempt. A line with two unwraps is two\nfindings.",
  'ts-challenge-001':
    '# Challenge: Type-Safe Counter\n\n## Requirements\n\nCreate a `Counter` class that tracks a numeric count with the following features:\n\n1. **Private count property** - Should store the current count value\n2. **Constructor** - Optionally accepts an initial count (defaults to 0)\n3. **increment()** - Increases count by 1 and returns the new value\n4. **decrement()** - Decreases count by 1 and returns the new value\n5. **getValue()** - Returns the current count without modifying it\n6. **reset()** - Resets count to 0 and returns void\n\n## Constraints\n\n- The count must be a `number` type\n- All methods must have proper type annotations\n- The class should prevent negative counts (throw an error if decrement would go below 0)\n\nWrite your complete implementation below:',
  'ts-challenge-002':
    '# Challenge: Generic Array Utilities\n\n## Requirements\n\nImplement the following generic array utility functions with proper TypeScript types:\n\n1. **first<T>(arr: T[]): T | undefined** - Returns the first element or undefined\n2. **last<T>(arr: T[]): T | undefined** - Returns the last element or undefined\n3. **sum(arr: number[]): number** - Returns the sum of all numbers\n4. **unique<T>(arr: T[]): T[]** - Returns array with duplicates removed\n5. **groupBy<T, K extends string | number | symbol>(arr: T[], keyFn: (item: T) => K): Record<K, T[]>** - Groups array items by a key function\n\n## Constraints\n\n- All functions must be properly typed with generics where applicable\n- Handle edge cases (empty arrays, undefined, etc.)\n- Do not mutate the original arrays\n\nWrite your complete implementation below:',
  'ts-challenge-003':
    '# Challenge: Promise Retry Utility\n\n## Requirements\n\nCreate a `retry` function with the following features:\n\n1. **retry<T>(fn: () => Promise<T>, options?: RetryOptions): Promise<T>** - Retries a failed promise\n2. **RetryOptions interface** - Configuration for retry behavior\n3. **maxRetries** - Maximum number of retry attempts (default: 3)\n4. **delay** - Initial delay in ms (default: 1000)\n5. **backoff** - Exponential backoff multiplier (default: 1, i.e. no growth unless the caller opts in)\n6. **shouldRetry** - Optional predicate to determine if should retry\n\n## Constraints\n\n- Implement exponential backoff (delay * backoff^attempt)\n- Only retry on rejected promises\n- Return the result on first success\n- Throw error after max retries exhausted\n- Support custom retry condition\n\nWrite your complete implementation below:',
  'ts-challenge-004':
    "# Challenge: Type-Safe Event Emitter\n\n## Requirements\n\nCreate an `EventEmitter` class with the following features:\n\n1. **Generic type parameter** - Define event map interface\n2. **on<K>(event: K, listener: Listener<K>): void** - Subscribe to events\n3. **off<K>(event: K, listener: Listener<K>): void** - Unsubscribe from events\n4. **emit<K>(event: K, ...args: Args<K>): void** - Emit events with type-safe arguments\n5. **once<K>(event: K, listener: Listener<K>): void** - One-time subscription\n6. **removeAllListeners<K>(event?: K): void** - Remove all listeners\n\n## Constraints\n\n- Full TypeScript type safety\n- Listeners receive correct argument types\n- Support multiple listeners per event\n- once() listeners auto-remove after first emit\n- Handle listener errors gracefully (don't stop other listeners)\n\nWrite your complete implementation below:",
  'ts-challenge-005':
    '# Challenge: Mini Redux Store\n\n## Requirements\n\nCreate a `createStore` function with the following features:\n\n1. **createStore<T>(reducer: Reducer<T>, initialState: T): Store<T>** - Create a store\n2. **getState(): T** - Get current state\n3. **dispatch(action: Action): void** - Dispatch actions\n4. **subscribe(listener: () => void): () => void** - Subscribe to state changes\n5. **Middleware support** - Apply middleware to dispatch\n\n## Constraints\n\n- Full TypeScript type safety\n- Immutable state updates\n- Middleware chain support\n- Unsubscribe function from subscribe()\n- Action types must be string literals\n\nWrite your complete implementation below:',
  'ts-challenge-006':
    "# Challenge: Type-Safe Query Builder\n\n## Requirements\n\nCreate a `QueryBuilder` class with the following features:\n\n1. **select(...columns: string[]): QueryBuilder** - Select columns\n2. **from(table: string): QueryBuilder** - Specify table\n3. **where(condition: WhereCondition): QueryBuilder** - Add WHERE clause\n4. **orderBy(column: string, direction?: 'ASC' | 'DESC'): QueryBuilder** - Add ORDER BY\n5. **limit(n: number): QueryBuilder** - Add LIMIT\n6. **offset(n: number): QueryBuilder** - Add OFFSET\n7. **join(table: string, on: string): QueryBuilder** - Add JOIN\n8. **build(): { query: string, params: any[] }** - Build final query\n\n## Constraints\n\n- Method chaining support\n- Parameterized queries (prevent SQL injection)\n- Type-safe column references\n- Support multiple WHERE conditions (AND/OR)\n- Build valid SQL for PostgreSQL\n\nWrite your complete implementation below:",
  'ts-review-001':
    'You asked a model for a helper that fetches every page of a paginated API and\nreturns the records. It produced this, along with tests. The tests pass.\n\nIt is still wrong: under some inputs it silently returns fewer records than the\nAPI has. Nothing throws, nothing logs, and the shape of the result is correct —\nwhich is exactly why this class of bug reaches production.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'ts-review-002':
    'This one is real. It cost most of a day.\n\nEvery server-rendered page of a site started returning 500 with an error inside\na well-known library, in code that was working exactly as designed. Two\nconfident explanations were wrong before anyone realised the reported error was\nnot the failure at all — it was a second failure, caused by the first, thrown\nfrom a hook belonging to the plugin that had already died.\n\nThe mini plugin system below has the same shape. `createApp` reports the wrong\nerror, and a caller debugging it will go and read the innocent plugin.\n\nMake the original error survive. The reported failure must be the one that\nactually happened first.',
  'ts-review-003':
    "You asked a model to save a batch of items and return the saved records. It\nproduced this, with tests. The tests pass — `save` really is called once per\nitem.\n\nEvery caller receives an empty array. `forEach` invokes the async callback\nand throws the returned promise away; the `await` inside only sequences work\n*within* each callback, not the callbacks within the function. `saveAll`\nreturns at the first opportunity, `results` fills in afterwards, unobserved.\nThe shipped suite asserts that `save` was called — true immediately — and\nnever awaits the function's own return value for content, which is the only\nthing a caller can see.\n\nThis is the most common async bug in generated TypeScript, and it survives\nreview because the code *contains* an await. It is just aimed at nothing.\n\nFind the defect and fix it. You are graded on tests you cannot see.",
  'ts-spec-001':
    'Ask for "a function that turns a title into a URL slug" and you will get\nsomething back that works on `Hello World`. It will also do something with\n`  C++: A Guide!  `, and what it does is a decision somebody made without\ntelling you.\n\nThis is the most common way work goes wrong: the request was coherent, the code\nis coherent, and they are about slightly different problems. The gap only closes\nwhen the behaviour at the awkward inputs is written down.\n\nHere is the description, stated properly:\n\n> `slugify(title)` returns a URL slug. The result is lowercase. Any run of\n> whitespace becomes a single hyphen. Characters that are not letters, digits or\n> hyphens are removed. Runs of hyphens collapse into one. Leading and trailing\n> hyphens are removed. An input with nothing usable in it returns an empty\n> string.\n\nBelow are six implementations. One of them satisfies that description. Five\nsatisfy a reading of it that skips one sentence — and all five look fine.\n\n**Your job is not to write `slugify`.** It is to write the cases that accept the\ncorrect implementation and reject each of the other five.',
  'ts-tool-001':
    'This exercise is real. This platform shipped 91 exercises, and two of them\ncontained a test that asserted nothing — it called the function, ignored the\nresult, and passed as long as the code compiled. Such a test cannot tell a\ncorrect implementation from a wrong one, so an exercise resting on it grades\neverybody as correct.\n\nNobody found those two by reading. A rule found them in 40 milliseconds, and\nthen kept finding them every time somebody wrote a new exercise.\n\nThat is the move: when a check is worth doing more than twice, stop doing it and\nbuild the thing that does it. Write `findAssertionlessTests`.',
  'ts-tool-002':
    'This exercise is real. This platform shipped a progress page that hydrated\nwith `Hydration completed but contains mismatches` — after which client-side\nnavigation misrendered until a hard refresh. The cause was one line: a\nnested `<template>` element with no directive. The server compiler emits\nfragment markers for it; the client compiler builds different vnodes; the\ntwo sides disagree forever after.\n\nNobody found it by reading — the wrapper looks harmless, which is why it\nsurvived review. A sweep found it in milliseconds, and the fix was deleting\nthe wrapper. The sweep deserves to exist as a rule.\n\nWrite `findBareTemplates`. It scans Vue single-file components and reports\nevery *nested* `<template>` whose opening tag carries none of `v-if`,\n`v-else-if`, `v-else`, `v-for`, `v-slot`, or the `#` slot shorthand. The\nroot `<template>` of the SFC — the first one in the file — is the component\nbody and is never reported.',
  'vue-challenge-001':
    '# Challenge: useLocalStorage Composable\n\n## Requirements\n\nCreate a Vue composable `useLocalStorage` with the following features:\n\n1. **Accepts two parameters**: `key` (string) and `initialValue` (any JSON-serializable value)\n2. **Returns a ref**: Reactive reference that syncs with localStorage\n3. **Persists to localStorage**: Value is saved on change\n4. **Reads from localStorage**: Initial value comes from localStorage if available\n5. **Handles JSON serialization**: Properly stringify/parse values\n6. **Type-safe**: Works with TypeScript generics\n\n## Constraints\n\n- Handle localStorage being unavailable (SSR, private browsing)\n- Handle JSON parse errors gracefully\n- Sync across tabs using storage event\n- Use Vue 3 Composition API\n\nWrite your complete implementation below:',
  'vue-challenge-002':
    "# Challenge: Debounced Search Component\n\n## Requirements\n\nCreate a `DebouncedSearch` Vue component with the following features:\n\n1. **Search input** - Text input for search queries\n2. **Debounced search** - Wait 300ms after typing stops before searching\n3. **Loading state** - Show loading indicator while searching\n4. **Results display** - Display search results in a list\n5. **Error handling** - Show error message if search fails\n6. **Clear button** - Button to clear search and results\n7. **Emit events** - Emit `search`, `results`, and `error` events\n\n## Props\n\n- `debounceMs?: number` - Debounce delay (default 300)\n- `placeholder?: string` - Input placeholder\n- `searchFn?: (query: string) => Promise<SearchResult[]>` - Optional search function\n\n## Constraints\n\n- Cancel pending requests when new search starts\n- Don't search empty queries\n- Handle component unmount during async operations\n- Use Vue 3 Composition API with `<script setup>`\n\nWrite your complete implementation below:",
  'vue-challenge-003':
    '# Challenge: Virtualized List\n\n## Requirements\n\nCreate a `VirtualizedList` Vue component with the following features:\n\n1. **items prop** - Array of items to render\n2. **itemHeight prop** - Fixed height per item (pixels)\n3. **containerHeight prop** - Visible container height\n4. **overscan prop** - Number of items to render outside viewport\n5. **emit scroll event** - Emit scroll position\n6. **emit reach-end event** - Emit when near end (infinite scroll)\n\n## Constraints\n\n- Only render visible items + overscan\n- Maintain scroll position\n- Use requestAnimationFrame for scroll handling\n- Support keyboard navigation\n- Use Vue 3 Composition API\n\nWrite your complete implementation below:',
  'vue-challenge-004':
    '# Challenge: Form Validation Composable\n\n## Requirements\n\nCreate a `useForm` composable with the following features:\n\n1. **initialValues** - Initial form values object\n2. **validationRules** - Validation rules per field\n3. **register(name)** - Register field with validation\n4. **handleSubmit(onSubmit)** - Handle form submission\n5. **errors** - Validation errors ref\n6. **touched** - Touched fields ref\n7. **isSubmitting** - Submission state ref\n8. **isValid** - Form validity computed\n9. **resetForm()** - Reset to initial values\n10. **setFieldValue(name, value)** - Manually set field value\n\n## Constraints\n\n- Support multiple validation rules per field\n- Async validation support\n- Real-time validation on blur\n- Validate on change (optional)\n- Type-safe with TypeScript generics\n\nWrite your complete implementation below:',
  'vue-challenge-005':
    "# Challenge: Infinite Scroll with Caching\n\n## Requirements\n\nCreate an `InfiniteScroll` Vue component with the following features:\n\n1. **fetchData prop** - Async function to fetch page of data\n2. **itemHeight prop** - Fixed/predicted item height\n3. **threshold prop** - How close to bottom before fetching\n4. **Cache results** - Don't refetch loaded pages\n5. **Loading states** - Per-page loading indicators\n6. **Error handling** - Retry failed pages\n7. **Virtual scrolling** - Only render visible items\n\n## Constraints\n\n- Cancel pending requests on unmount\n- Handle scroll position during data loading\n- Support pull-to-refresh\n- Debounce scroll events\n- Memory-efficient (cleanup old cache)\n\nWrite your complete implementation below:",
  'vue-review-001':
    'You asked a model for a small cart composable: items, an `add` function, and a\nrunning total. It produced this, with tests. The tests pass.\n\nThe total is frozen at its birth value. `ref(sum(items))` runs `sum` once, at\nsetup, and stores the resulting number — a snapshot wearing the type of a\nreactive value. Nothing about it ever recomputes, because nothing was ever\ntold to. Every shipped test reads the total exactly once, right after setup,\nwhich is the single moment a snapshot and a formula agree.\n\nThis is the most common reactivity bug in generated Vue code, and its tell is\nin the types: the total is data, but it should be a derivation.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'vue-review-002':
    'You asked a model for a search composable: hold a query string, and each time\nit changes, call the provided `onSearch` with the new value — skipping blank\nqueries. It produced this, with tests. The tests pass.\n\n`onSearch` never fires. Not once. `watch(state.query, …)` evaluates\n`state.query` immediately — producing a plain string, `""` — and hands that\nstring to `watch`. A string carries no subscription; there is nothing for Vue\nto track. Vue logs a warning about exactly this, but a warning is not a\nfailure, and the shipped tests only assert on state they set themselves, so\ngreen stays green.\n\nThe one-character spelling difference between "a value read now" and "a\nsource read on every change" is the whole exercise.\n\nFind the defect and fix it. You are graded on tests you cannot see.',
  'vue-review-003':
    "You asked a model for a composable that runs a callback when a given key is\npressed — the standard keyboard-shortcut helper. It produced this, with\ntests. The tests pass.\n\nThe listener is never removed. Every component that ever used this\ncomposable is still wired to the document after unmount: handlers firing on\ndead components, state updates against torn-down trees, and — in a\nlong-lived app — one more leaked closure per navigation, forever. The\nshipped tests mount and press keys; not one unmounts, and unmounting is\nwhere this composable's only obligation lives.\n\n`addEventListener` in setup is a loan, not a gift. Find where it should have\nbeen returned. You are graded on tests you cannot see.",
  'vue-spec-001':
    'This site\'s marginalia — "last used 3m ago", "recorded your reflection\n2h ago" — runs on a function like this one. Ask for "format seconds as a\nrelative label" and you will get something that turns ten minutes into\n`10 minutes ago`. It will also do *something* with 30 seconds, with 90\nseconds, and with exactly one minute — and each of those somethings is a\ndecision somebody made without telling you.\n\nHere is the description, stated properly:\n\n> `relativeLabel(deltaSeconds)` renders how long ago something happened.\n> Under 45 seconds it is `"just now"`. From there to 45 minutes it renders\n> whole minutes, **rounded to nearest**, as `"N minutes ago"` — singular\n> `"1 minute ago"` when N is one. Everything else renders whole hours,\n> rounded to nearest, with the same singular rule.\n\nBelow are five implementations. One satisfies that description. Four\nsatisfy a reading of it that skips one sentence — and all five agree on\nten minutes.\n\n**Your job is not to write `relativeLabel`.** It is to write the cases\nthat accept the correct implementation and reject each of the other four.',
  'vue-tool-001':
    "This exercise is real. This platform's Vue track ships a search composable\nwhose original sin was one line: `watch(state.query, …)`. The expression\nevaluates immediately — to a plain string — and a string carries no\nsubscription, so the watcher never fired. Not once. Vue does log a warning,\nbut a warning at runtime on a code path nobody exercises is a message to no\none.\n\nThe shape is fully visible in source: `watch(` followed by a member\nexpression. It does not need a runtime to be caught — it needs a rule.\n\nWrite `findValueWatchers`. It scans files and reports every `watch(` call\nwhose first argument is a member expression — an identifier, a dot, and\nmore identifier — rather than a function or a bare identifier. A getter\n(`watch(() => state.query, …)`) is the fix and never a finding; a bare ref\n(`watch(query, …)`) is legitimate; `watchEffect(…)` takes a function by\nconstruction and is never a finding.",
}
